(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 900,
	height: 450,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"},
		{src:"sounds/reiam.mp3", id:"reiam"}
	]
};



lib.ssMetadata = [
		{name:"index_atlas_", frames: [[2422,0,600,569],[0,0,2420,1195]]}
];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._4448ce33c895d1430259cfb071f082025baf0760 = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._54058338_p0 = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.text = new cjs.Text(" PLAY", "18px 'PingFang SC'", "#FFFFFF");
	this.text.textAlign = "center";
	this.text.lineHeight = 27;
	this.text.lineWidth = 100;
	this.text.setTransform(-0.6,-11.9);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AoMDmIAAnLIQZAAIAAHLg");
	this.shape.setTransform(0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AoMDmIAAnLIQZAAIAAHLg");
	this.shape_1.setTransform(0.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.text,p:{scaleX:1,scaleY:1,x:-0.6,y:-11.9}}]}).to({state:[{t:this.shape_1},{t:this.text,p:{scaleX:1,scaleY:1,x:-0.6,y:-11.9}}]},1).to({state:[{t:this.shape_1},{t:this.text,p:{scaleX:1.386,scaleY:1.386,x:-0.7,y:-17.2}}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.6,-23,105.2,46);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._4448ce33c895d1430259cfb071f082025baf0760();
	this.instance.setTransform(0,0,0.647,0.647);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,388,368);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAXBFIgDgMIAOACQAKgBAFgCQAGgCABgDQAEgJAAgmIg+AAIAGgyIAMABIgHAoIAiAAIAIg0Ig3AAIAAgLIBDAAIgJA/IARAAIgBAsIgCAOIgDAIQgEAEgGACQgHACgLAAIgOAAgAg2BAIAAhAIgKARIgGgKIAIgNIAHgOQAEgMAFgWIgUAAIAAgMIA3AAIAAAMIgYAAQgGAYgEAMIAeAAIAABQIgLAAIAAgJIgRAAIAAALgAgrAqIARAAIAAgyIgRAAgAgHAjIAAgLIA4AAIAAALg");
	this.shape.setTransform(85.5,13.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgyBKIAAhYQgHAJgLAJIgEgKIAMgPIALgQIAIgRIAHgTIALAGQgJAYgGAKIAABrgAAqBEQgHgEgGgHQgIgMgEgHIgIgZQgCgHgDgUIghAEIgBgLIAhgEQgCgVAAgaIAMAAQAAAaACATIA0gGIABALIg1AHQACAPACAJQADAMAEAKQAEAJAFAHQAFAHAEADQAFADAEAAQADAAADgHIAEgXIAKAGIgEARQgCAHgDAFIgEAGIgGABQgGAAgGgEgAAlgzIgOgNIAIgHQAJAIAPAQIgIAIQgEgFgGgHg");
	this.shape_1.setTransform(69.7,13.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgGA/QAJgGAJgGQAIgFAHgHQgIgKgFgLQgHgLgDgLQgCALgCAMIgGAUIgJASQgFAJgGAGIgJgHQAFgGAJgNQADgHAHgRIAGgbIACgiIAAgQIgTAAIAAgKIBJAAIAAAHIgJAlIAYAAIAAAHIgEAOIgFAOIgGANIgJAMIAPAMQAIAGAJAGIgHAJIgRgMQgJgFgGgHQgIAHgJAHQgJAGgJAFgAAGgnIAAAJQABAJADAIIAGAPIAIAPIAKANQAGgGAHgNIAHgWIgZAAQAEgPAGgdIghAAgAhJAqIAWgFIAAg3IgTAAIAAgLIATAAIAAgqIAMAAIAAAqIATAAIAAALIgTAAIAAAyIASgGIAAALIgYAJIgZAHg");
	this.shape_2.setTransform(53.9,13.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgSBGIAAgLIAwAAIALglIAJgrIALACQgIArgLAjIAfAAIAAALgAhIAtIAXgFIAAg3IgVAAIAAgLIAVAAIAAgqIANAAIAAAqIAUAAIAAALIgUAAIAAAzIAWgHIAAALIgbAJIgcAIgAABAOIgHgfIAIgDIAJAeIAIAlIgKADIgIgkgAgNggIAAgLIAkAAQgFgMgFgMIAMgCIAJAaIAjAAIAAALg");
	this.shape_3.setTransform(37.8,12.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,123.6,26.4);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._54058338_p0();
	this.instance.setTransform(0,0,0.352,0.352);

	this.btn = new lib.Symbol1();
	this.btn.setTransform(71.5,142.7,1.157,1.023,0,0,0,61.8,13.2);
	new cjs.ButtonHelper(this.btn, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,851.8,420.6);


// stage content:
(lib.Untitled1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		this.stop();
		this.btn_play.addEventListener('click', function(e) {
			_this.play();
		});
		playSound("reiam");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(65));

	// Layer 3
	this.btn_play = new lib.Symbol6();
	this.btn_play.setTransform(492.2,415);
	new cjs.ButtonHelper(this.btn_play, 0, 1, 2);

	this.timeline.addTween(cjs.Tween.get(this.btn_play).wait(65));

	// Layer 2
	this.instance = new lib.Symbol4();
	this.instance.setTransform(717.1,225,1.223,1.223,0,0,0,194,183.9);
	this.instance.cache(-2,-2,392,372);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FDFCFB").s().p("EAU1AjqIiqAAIjBAAI2aAAI2cAAIn6AAIAA2cIAA2bIAAy3IAAgvIAAi2IAAkBIWcAAIWbAAIWcAAIH6AAIAAG3IAAAvIAACEIAAAgIAAABIAAAPIAAAGIAAAEIAAAHIAAAkIAAA7IAAALIAAAVIAAAJIAAAQIAAAQIAAAeIAACAIAAAcIAAAmIAAABIAAArIAAABIAAAWIAAAxIAAAQIAAAcIAAAFIAAAgIAAALIAAAFIAAATIAAAJIAAAXIAAAWIAAABIAAAcIAAAWIAAADIAAABIAAAVIAABaIAAAfIAAAQIAAA0IAAAfIAAAPIAAATIAAAqIAAABIAAAHIAAAIIAAAIIAAABIAAAcIAAAXIAAAsIAAAhIAAAQIAAAeIAAAaIAAABIAAAPIAAAHIAAABIAAAbIAAAuIAAAWIAACIIAAASIAAAIIAAAbIAAAiIAAAaIAAAXIAAABIAAAZIAAAkIAAAYIAAAFIAAAMIAAAhIAAATIAAABIAAAsIAAAgIAAATIAAAuIAAACIAABZIAAAhIAAAEIAAAiIAAA/IAACSIAAA0IAAAOIAAAmIAAACIAAAOIAAAPIAAAMIAAAGIAAAGIAAAFIAAADIAAAFIAAAgIAAAMIAABaIAABMIAAAVIAAAlIAABMIAAAMIAAACIAAABIAABjIAABpIAAAtIAABSIAAAoIAAA6IAABlIAADmIAAEAIwyAAgEACgAhCQATACATAAIgSgGIgBAAQgFAAgOAEgEACXAhAIABABIAIABIAAgIIAAgIQBUgCBlgGIAIAAQAwgvAogQQAAAkAtg6QAlgyAugqIAAgIQAWgGAGAMQAAABAAAAQABAAAAABQABAAAAAAQABAAABAAQA6AGAKgkQAAgBABAAQAAAAABgBQAAAAABAAQABAAABAAQAWgeAggVQACgBAAgEQAEAAACgCQACgCAAgEQAUgDAKgOQACgDAAgEIAAgIQAQgEAOgHQACgCAAgEIEijeQADgCAEAAQAPgRAXgKQACgBAAgEIAYgRQAigZAcggQACgCAAgEQAEgFADgEQABgEAAgDQAVgKANAIQACABAEABQAAAEgCACQgCACgEAAIAAAIQgEAAgCABQgKAGgIAJIAAAIIAAAIIgIAAQASBPgJBRIgBAIIAAAJIgEAAQACBRgOA/QABAjALAcQAAAAAAAAQABABAAAAQABAAAAAAQABAAABAAQAQAMASALQACABAEAAQAaAEAYABQBYACA9gyQACgBAAgEIAAgIQAOgKAIgPQACgDAAgEQAXghAIgwIABgIQAagKAFgdIABgIIAAgIIAAg5QAVg8gJhUIgEAAIgBgIQgHgUAAgdQAAgEgCgCIgHgMQgKgYADglQgFgTgOgKIgFgEIAAgEIgFAAIgCgCQgTgSgGgYQAKgFAJgCQAJgCAJAAQALgBAMAEIANAEIADACIAEAAQAEAEAFACQADACAEAAIAAAIIAAAIQAEAKAFAIIAAAAIAJASIABADQABABAEAAQALANABAbIAEAAIAJAmQARA/AXAcIACgBQAEgBASAiIAIAQQAPA9A4AQQALAEAOACIAYABIAAgEQAPgJAMgKQAbgYATghQAKgRAHgVIAFgPIABgFIAAgCIAFgNQAIgdgEgpIAAgDIAAgCIgBgIIAAgJIgBgJQgDgigGgjQgGgogLgpIgPgxIgGgRIgBgIQgShlglhTQAKgPAMgLQACgCAAgEIAAgIQAEAAACgCQACgCAAgEQAIgEAGgGQACgCAAgEQABAAABAAQABAAAAAAQABAAAAgBQAAAAAAAAQALg/gngQQAAgFgBgCQgDgGgEgDIgBgIQgIg0gfgdIAAgIQgGgog6g4QAAgBAAgBQAAgBgBAAQAAgBAAAAQAAAAAAAAQgRgHACgVQAAgEgCgBQg6gcAEBpIgIAAIAAAIIgWgJQhOgPglAgQAAgEgBgBQgSgLgFgYIAAgIIAAgIQAOgSgFgmIgBgIIABgIQAKhHgbghIAAgIQAAgQgIgJQgEgDgBgGIgDgKQgPAAgRgMIAAAPIAAAIQgEAAgDgBQgXgMgCgjQANACgEgSIgBgIIAAgIIAAhIQASggAhgdQAXgVAOAaQgOAWAZAgQABACAEAAIAAAIIAAAIQAAAEgBADQgDAFgEAEQAUAIAAAgIAEAAQAAAEgCACQgCACgEAAQADBRAigkQAMgNgJggQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgIgXgEgYQBOgfAzAqIAIgbQgJgagSgEQgMgEgRAGIgQAIQgCABgDgOIgBgGQgDgTgNgSIgDgFQAAgDACgBQARgMATgOQAfgYAkgiIgIACIg2AIIguAIIgdAGQAAgDgBgEQgMgXgTgRIgBgIQgOg2ghAfIAAAGIAAAIQgEAAgDgBQgugfgjgGQgEAAgCgCQgCgCAAgEQAAgBAAgBQAAgBgBAAQAAgBAAAAQAAAAgBgBQhLgmhMADQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAAAgBAAQgtgLgKgZIAAgEQgZADAJg/IAAgIIAAgIQAIglAfgPQABAAAAgEIAIAAQApgCghgOQACgWAHAAIAHACQgvglAvABQASgKgigBQgCAAAHgYQAIghADgFQAMgkANAjQACAGANglIAAgEQhGgBgaBNIABAIQADA1gcAcQACANAWgCIAAAFIgIAAIgQAAIAAAHQgBAAgBABQAAAAgBAAQAAAAgBAAQAAAAAAABIgUBPQABBQAZAeQACACAEAAQAEAgAIAeQAAAAAAAAQABAAAAAAQABAAAAAAQABAAABAAIAAAJIAAAIQAAABAAAAQAAABAAABQAAAAgBABQAAAAAAAAQgHAEgIAAQAAgEgCgEQgRgkgtgLQAAgEgCgCQgPgOgHgUQgEAAgDgCQgOgJgDgVQAAgEACgCQAwgrhKARQAIgEAGgGQACgCAAgEIAIgIIAIgIQgdgYgTghQAAgDgCgDQgGgJgIgJQAAgDgCgCQgpgtgOBKQAAgEgBgDQgPgdhAAEIAAAIIgIAAQgogEgYAMIgIAAQgGAaAMAJQACABAAAFQAPBVANBbIAEAAQAAAFgCABQgCACgEAAIAAAGIgIAAIAPApQABADAAAEIgIgBQgagHgGAxIAAAIIAAAIIgEAAQABAagNAFIAABBIAAAIQgIgEgEACQgXAPglArIAAAIIAAAIQgEAAgCACQg7BihgA8IAAAIQgEAAgDACQgFADgEAEQgEgBgDgBIgJgHIAAgIIAIAAQBUhJBLhRQACgCAAgEIAAgIQAqg6AdhHIABgIIAEAAQAGgggigYQAAgDgCgDQhZhhiegfIgBgFQgPgDgQAAIgBgEQhQgMhIgQQAyAqALAeIgEgIQhbggBAAzQACACAAADQgEAAgCgCQgvgmhLAYQgEAAgDgCQgjgTgOgrIAIgIQgzgdhNgLIAAgIQARAFgBgNIAAgIIAIAAQB4ADiAgLIgIgBQhBgSgOATQAGAVgSgLIgHgEQg7gghigfQAdAkApAYQACABAAAEQAgAZgYAGIgIABQgEAAgDgCQgTgMgegCQgEAAgDgCQg0gshGgbQAAgEgCgCQgSgRgUgQQgEgBgBgCQgSgXgZgPIAAgIIAAgIQgIg2gYgaIgFgQQg8hohHhpQAbBTgTAmIgIgIIAAgJQABgVgJgLQgDhZgShCQgWhTgeAmQAjAxgRBAQgCADAAAFIgIAAIAAAHIAAAIQgEAAgDgBQgFgDgEgEQAAgEgBgDIgHgIQABgigVgMIgEgDQgdAUAFg8QANABgEgSIgBgHQAIAAAHgDQABgBAAgEIAdBHQAGgZgLgeQANglgSgtQgihZAnAjIAEAAQgNhHgvhCIAIAAIAIAAIAIAAQAmBLAvAQQACABASA1QAXAMgEAWQgFAeAKghIAMAHQAEACAAAIQAcAfAXAnQABACAEAAQANAGAHARQAAAAAAAAQAAABABAAQAAAAABAAQABAAABAAIAAAIQAAAEgCAEIgGAIQAEBWAThGIABgIQAbANAJAjQAAAAAAAAQABAAAAAAQABAAAAAAQABABABAAQgEA/ATApQABAEAAADQAJglgQgzIgBgHQAIAIAJAFQADACAEAAIAAAIIAAAIQAPA9gDAsIAEAAQAaA2BHAZIAIABQgdgig6gpQgCgBAAgEIgBgIQgNgrgKgtQAkAzAPgQQALgMgOABQAAgEACgEQAOgsgggkQgDgogBghQgDhbgxAbQAAgEgCgCQgLgMAFgeQAOgDgCgVIAEAAQBKACgmgXIAAgEQAAgEgEgEQAagWgQgNQghgegpgfQAAgEgCgBQhhhHhVgsQAQA0AABEIAAAIQgEAAgEgCQgEgBgEgFIAAgHQgCh0hHgtQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBAAAAgBIhHgTQgMgRgIgIQgQgUgcgDQAAgFgCgCQgRgfgdgTQAAgDgCgCQgUgVgSgWQBHgIhPgXQgJgDgwgeIAAAIQgEAAgBgBQgig7hpgUQALA+A+AtQAKAHAVgCQBABNBDBJQACACAEAAQAFAbARAQQACACAAAEQAmAhAGBOIAEABQAFArADAtIAAAJQgBAAgBgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQgFgMgOgDQgBAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQgShNgxgqQAAgEgCgDQgeg2gxgjQAAgFgBgDQgWgugxgTQAAgEgBgDQgfgwgoAAIgBgIQgNgjgqgGQAsAjgEAlIAAAIQgEAAgDgCQgYgSgxgTIAAgFQgqAKhHgeQAGAnAcAQQACABAEAAQASAjASAkQABABAEAAQAHAtAXAeQACACAAAEIgEAAQAAAwgcggQgMgVgQgRQg/hIAaA+IAAAMQgVgwhDg1QApBrAqBEQABACAEAAQAAAEgCACQgCACgEAAIAcBXQAAAAABABQAAAAAAAAQABAAAAAAQABAAABAAQA2BFgvgbQgDgCgEABQAAgFgBgBQhmg1g5g+IAAAEQgPg8ghgIIgBgIQgRg3gWgxQARBnAlBSQACADAAAEQAEAIAGAGQACACAEAAQAKAuAYAhQACACAEAAQAOAaAJAeQABAEAAADQgEABgBABQgFAMgOADQAAgCAAAAQAAgBAAgBQAAAAgBgBQAAAAAAAAQgbgHgMgVQAEgPgFgEQgqgegVhXIAAgIQAKhfg6AHQAgCKArBdQABACAEgBQAMAlAaAWQACACAAAEQAhA6gJhDIAAgHIAJAGQADABAEAAQAQAlAaAaQACACAEAAQACAiAXANQADABAEAAQAdBJAHhRIAEAAQAOADAGAMQAAAAAAAAQABAAAAABQABAAAAAAQABAAABAAQAAAEACADQAOASgYAHIAAAIIgIAAIgIAAQASAegBALIgBAIQA4AeAiAgQADACAEAAQAbAaAQAtQAAAAABAAQAAAAABABQAAAAABAAQABAAABAAQAKAiANAeIABAIQASAuAZAoQABADAEAAQABA2AWAFQABAAAAABQAAAAAAAAQAAABAAABQAAAAAAACQgCBGA6AKIAIAAQAAADACADQAKANgsgDQAEAIAAAIIgEAAIgIAAIgIAAQAGAkgFAkIgBAIIAAAIIgIAAIAAgIIAAhAIgBgIQgShDglBjIAAAIIgEAAQARAzgtA1QgGAtAMAaQACAEAAADQgJAiAZACIAAAFQAWA2AoAkQACACAAAEQApAPAhAXQACACAEAAQAEAAACACQACACAAAEQAPANAaACIAIABQAAAEACACQACACAEAAIAAAIQAMAUAdASQADADAEAAQARgFACALQAAABABAAQAAAAABAAQAAAAABAAQABABABAAQAtAKA7gDIAIAAQAWAlAWgVQASACACgZQAxAGAogGIAIAAQA6AJAiAWIgMAAQgQATBBgHQAVgBAKgLQBSAsAxBDQACACAEAAQAAABAAABQAAAAgBABQAAABAAAAQAAAAgBAAQgLAEgkgQQAlAjAeArQACACAEAAQATAgANgMIgBAMQgCAnALAZQAAAFACACQACABAEAAIAAAIIAAAIQgLANgBAbQgEBMgYgTQAEgEABgFIADgMIg4BtQgEAAgCACQgJAPgSAHIAAAIQgEAAgDABQgFADgEAEQgEAAgDgBQgFgDgEgEIAAgIQAUgQATgSQACgCAAgEQAqg1gOgaQAAAAAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAIAAgIQAGg6gOgnQAAgDgCgEQgGgIgIgIQAAgFgCgDQgNgagagPQAAgEgCgCQgQgQgWgKQAAgEgBgBQg+gghBgbQgEAAgDgCQhDgeg/AoIAAAIIgEAEIgEgEQgVAPgzA5IABgIQADgkgUgMQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgQhCgsAjIgBgIQgGgXghgKQg1gDAQAeQAKATgFgFQgigjhPALIAAAIIgIAAIgYAAIgIAAIgYAAQAmBjBLAUIAIABQAWApgNAoIgBAIIgEAAQgIAngtAZQAdAmhGgbQgZgKgmAXQApAXA3AFIAAgFQAEAFAFACQADACAEAAQAAAEgCACQgCACgEAAQgEAAgBACQgJAMgagGQAAgBAAgBQAAgBAAAAQAAgBAAAAQgBAAAAAAQglgHhCADIgEAAIgEB4QgEAAgDACQhLAfgOA3QA0gVgPArQgFANAYgjIgDAHQgBAFgEAEQAJAWgBATIALgHQALgIAGgGQAEgDAIAAQgzgeA7ADQANAAgHAIQgLALANgBQAjArAAgrQgBgOgRgLQgHgFAOgZQAcgJAMAEIAAgDIAEAAQgTAzAnAdQBLABg7AHQgbADAbAMQgogGgMAIIgMAGQATAMgjAVQgCAogQgZQgagkAcA9QgEAAgDgCQhEgogtAyIAAAEQBTgagjA2QgEAAgBABQgVAvBCAYQAAAEgCACQguAsggAOQgEgPgKgMIgCgFQAKg/gqAfQgjghABgeQACgqgxAJQgEAAgBgCQgSgjgZgcQAAgDgBgEQgdhFgigzIAAgIQABhAgxAPIAZAgQgNAeAkALQAZAyATA9QAAAAAAAAQABAAAAAAQABAAAAAAQABAAABAAIgBAJQgIAugngmIAAgIQgGgvgygqQAAgDgCgEQgNgegRgaQgMgcAAALQADBAgfAQQgCAeAigCIAAAFIAAAIQgEAAgEABIh5AvIAAAIIgHABQgrANgeAaQgEBQA9AQIAHAAQArAJAYAdQABACAEAAQAIBEBCgGQAJAAAIARQAGANAIANQgsByBlAtQADABAEAAQAlgRg9ABIgIAAQgVgrgKg1IgBgIQAbhPgrg1IAAADQg6AygVg6QgCgDAAgFQBHgEhCgeQgTgIhCgGQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAAAgBAAQgqgRgFgzQAbgZAkgTQAAAAAAAAQABAAAAgBQAAAAAAgBQAAgBAAgBQBSgpAgAFQAMABATgGQgGAWAMAGQACABAAAEQgLALACAKQgHgbg4AWIAuAbQACABAAAEQgEAAgEgCQgfgKgJAUQAZAjAdgkQACgDAAgEQAMgUAHAKQABACAEAAIAAAIIgFAAQgMAugnACQAiAbARgWIABgFQgBgHAdAHQAOAOAMAQQACACAEAAIAAApIAAAHQAfBNAqAaQADABAEABQAPAIAFAXIAEABQAAAEACACQACACAEAAQgBAgAhAEIAAAEQAAAEACADQAJAQgTAZIAAgIQgfADgCgTQgBgRgDADQgeAjgVATQAtBIAzAAIAIAAQAAgvABAvQAAAQAQADQAHABAIgDQAAgoAxAPQAoANA4gNQAEAAACACQACADAAADIAAAFQA8AEAMAvQgYBAAYACQAqADgyALQgQANAcgJQAmgNAWAiQAOANgCgNQgIhHAUA/QAAAEgCACQgsAqhigoQAAgEgCgCQgvgnABg0IAAgDQhDAYhGgNQAqAYA9ALQAKABAKAKQArAqAzAhQAMgOAnAdQAnAdAWgsQBiAJAOhKIABgIQA2gKAiAPIAAgFQgRgoABgZQACgRgKAaQAGgiAogoQACgBAAgFQAJgHAOgEQAAgBABAAQAAAAAAgBQAAAAAAgBQAAgBAAgBQARAMAfgEIAIAAQAQAAAQAEIAAAEQANAJAIAKQAMAOAMAEQBJAag1AJQgOgCgIgKIgCgDQAOAjgugEIAAAZQAAAQgJAGIgNAMQANA4gwgCQAmBuA9hDQAGgHgEgIIgEAEQgoBAAchiQAEgOAIgIQBEgHAbBHIABAIQAaAnAmABIAEAFQAoAtAsgiQAUgUAQgaQAAgCAFAAQgHBnAlA7QACACAAAFQAQAXARgNQADgCAEgBQAtATAzANIAIAAIAEAAIgBAAQAagHAyATQAAAAABABQAAAAAAAAQAAABAAABQAAAAAAACQAxgHAegIIAIgCQA4AYA/AHgArXb8IACAFQgDg2g5AVQgFAWAPgNQAKgHAJAAQAQAAANAagA0KQfQA6ANgfgqQgDgFgEAAQgKAAgKAigA2bN+QALAOAcACIABAAQAVgfgSAAQgMAAgfAPgA0jM2QgEAAgBACQgPARgcAFQAwApAHgqQABgHgIgIIAIgBQBOgUAjgMIgBgDIgTgCQgyAAgzAegA0BE0IAXBRQgcA0AtAYQAeARABAzIAHAAQA1ANA0ALIABAIQAMBzBbgDQAAgDgBgCQg0gVgbguIgEAAQAHhPg7gJQgOAOgSgMQgqgYgOg7QgwADAPguQAHgSgCgGQgPgjgVgiIABAIgAZEINQAAAIAEABIAEADQAGAWAUgMQAngXgxAAIgYABgAz+IgIAEAFQAWgrgmgdQgHAvATAUgAxBHDQADABAEAAIAwAAIAIAAIAIAAQBJABAwgZIgIgBQiCgthvhBQAAgEgCgEQgCgFgEgEQAAgEgCgCQgTgRgLgZQAAgEgCgCQgxhEgFhvQgIgTgPAKIgBABQgKBhg3goQgmhngmhCIgEgGQAAATgYANIAAAIIAAAIIAAAWIAAAJIABAIQAFAVgOACIAAAQIAAAIQAIAgATAWQABACAEAAQAAAFgCACQgCABgEAAIAAAJQgEAAgDgCQgRgMgQAOQAKAKACAWIAEAAQARAUAlgmQACgCAAgEIAEAAQAAgIgEgJIAIAAQAeAXARAjQABADAAAEQgBAxAgAKQABABAAAAQAAAAAAABQAAAAAAABQAAABAAABQANAcANgKQADgCAEAAQANASAaAKQAAAAAAAAQAAABABAAQAAABAAABQAAABAAABQAeASAgARQACABAAADIABAIQAEAVgVgEQA8A1AdARgAYkG8IAAAFQAxgRgEAAQgDAAgqAMgA3BCjQgCgDAAgEIAAgIQAAgygYA6IAAAIQgBAAgBAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgEgXAAgYQAEgBACgCQACgCAAgDQAAgFgCgCQgKgSgEgYQAaAAgQgLQgCgBAAgDQAagWgQgDQg5gNg5gpQAAgEgCgCQgGgKgJgIIgEAAQgGgmguAGQADANAMAHQAAAAAAAAQABAAAAABQAAAAAAABQAAABAAABIgHABQgpAJg4AWQAcBPBFAmQADABAEAAQAAAFACACQAjAghFAaQASBABPgcIAAAEIgIAAQAOAWAiABIAIABQAOANAJgWIABgHQAOgaAIALQACADAAAEQAAAEgCADQgCAFgEAEQgGAaAOACIAAgEQBIAXgmhYgAbSBTQgLAHgSAaIAAAEQADAbAJAXQAPAhAHgiQAThagRAAQgDAAgEAEgAGpjTQhcAUiFAUQBrAaB2AOIAIAAQAcAQAkAHIAIABQBTAVA3AxQACACAEAAQBSA5ApA/QADAEAEgUQADgVgEglIgBgIQgrhnhthPIgIAAQAAgFgCgBQgSgSgUgRQAAgDgCgDQgOgWgoAEQAIAJAEAPQAAAAAAAAQABAAAAAAQABAAAAAAQABAAABAAQAAAEgBAEQgIAZgvgQQgBAAgBgBQgBAAAAAAQgBAAAAAAQAAAAAAAAQgIgUgcAEIAAAIIgIAAIgIABgAz6ADIAAAZQACAVAGgFQAsgpgoAAIgMAAgAz6grQA7APgRhnQgCgQAAgQIAAgIQAKgiAFgnIABgHIAAgIIAAgQQAEgBABgBQAig2gngRQAAgEgCgCQgXgRgHghQAAgIgEgGQgMgXgRgSQhChLg2gOIAAAHIAAAIQgEAAgCgCQgUgUgWgRQgEgBgDgBQgFgDgEgDIAAgJQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAAAQA4gMhBg5IAAAIQgEAAgBgBQgUgegXg5IAAgIQgCg0gmgsQgUAKAEA/QAFA6gdgbQAAgEgCgDQgCgFgEgEIAEAAQgIhTglhVQgHAQAMAnQAKAhgnAIQAAgEgCgCQgGgHgIgDIgBgIQgHgYgQgRQAAgDgBgEQgKgRADggQAAgEgBgDQgcgsgDhFQANABgEgRIgBgIQATglgDg8IAAgIQAOgCgFgVIgBgIQAQgQAAghIAAgHQASgSAOABIAIABQAEB1Ach2IAAgHQAigoATgHQADgBABAPQglBEAtARIAAgFQAngrABhVIAFgDQAHgFAEgIQhJgfAugQQAhgLg+gOQAEAAACgCQA3glAzgqIAAgDQhLAdgtAeIAAAIQgEAAgCADQg1A8gmBKIgIgBQgPgBgZAaIAAAIIAAAIIgEABQgIAfgMAYIAAAIQAAAEgBAEQgNArgSAmIAAAwIAAAIIABAIQAKBBgDAPQgEAAgDgBQgogXghggQAaBeAmAiIgGgDQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAgBAAgBQhFgHAWAOQADABAEAAQA3ABAiAWQADACAEAAIAAAIIgIABQglAFgTAZQAIAIAJAHQADACAEAAQA9AOgdBSIAEAEQAEAEAAAIQAUgJAWAXQACACAEAAQgGBTAVA2IABAHQADASAVgFIAAgFQAgABAUAuQABABAEAAQgIBJAggHIAIgBQAAAEACACQAOAPggADQAgBDAkhLIgEAAQASgogYgiQgCgCAAgFIAGgIQACgDAAgEIAIAAIAIAAQADAUALANQACADAAADQAAAEgCADQgCABgEAAQgBAqAPgaQACgDAAgEQAPAIAFAXQAAAAABAAQAAABAAAAQABAAABAAQAAAAABAAQAGAnAQAbQACACAAAEQA7CNAJB8IAEAAQBPhRgoiCQgJgdgWgJQALgUAXgSQACgCAEAAQAPAOAMAQQACACAEAAQAzAxgLBIIAAAIIAAAIQAGAlgOATIAAAYIAAAIIgEAAQABBNgdArgA1ThLQAyAhAJg3QAAgBAAAAQAAAAAAgBQgBAAAAAAQgBAAAAAAQgKAAgvAYgALiijIAAAIQgBA4AhAYIAEAEQAQg4gZhDIgDgJQABAPgZAZgAW8iTQANAFAyAJIANACQAKgVgnAAQgSAAgdAFgAJLkdQAmA6BJAYQAMgJAAgIQAEgvgIhAQgeAZgugcQgBAAgBAAQgBgBAAAAQgBAAAAAAQAAAAAAAAQARA4g6gNQAAAEACADgAP9kPQAbATALAgIAAAFQAngshPgQQAAADACABgASrjkQAnAKAzgDQBBgGAGgJIgBgDQgcgDgZAAQg8AAgvAOgAMikTQgJArArgPQAOgFAAgDQAJgugRAAQgNAAgbAagA3Zm3QgZA3gZAEQgCAWASACIAIAAIABAIQAEAagNAGQACBRAZgoQATggALAfQAHATAAgbQgSglgNgjIgBgIQAOgSgDgmQgCgYgEAAQgBAAgCAFgAgvk0QAvgWgvgaQAWACAKgIQAOgLgGhXQgDgSgMgBQhCgJgvggQg6gpgmAcIAAAIQgEAAgBgCQgZgmgKBJQAWAFASgEIAIgBQgDA9AagSQAFgDAFALIAHAQQAUAFAUAIQAIAMAGANQACADAAAEIgIAAIhwAAQAMAIANAHQADABAEAAQAlAfAHADQAlAUAfAKIgIAAQANAQAzgYgAEok/IAMgKQAUgQAhgTQA3AUBFglQAZgNAbgKIAIgBQA3gTgPgsQgEADgPgiQgFgJgCAFQgYBBg+hHIAAgIQAAgPgIgJQABAAABAAQAAAAABAAQAAAAABAAQAAAAAAgBQANgmgpAAQAAgEgCgDQgegigogXQAAgEgCgEQgCgFgEgEQAoAbAAgjIAAgQQgTAGglACIAAgIQABgMgSAEIABgIQAFgagOgGIAAgIIAAg4QAEgEADgFQABgDAAgEQAAgEgBgEIgHgIQAQgQAHgZQACgEAAgEQAAgEgCgDQgCgEgEgFQARgCgBgVIAAgIQAIgJAIABQALgbgDhGIgBAIQgIAogPAgIAAAJIAAAIIgEAAQABARgNgBIAAAHQgBAAgBAAQgBAAgBAAQAAAAAAAAQgBAAAAgBQgGgjgGhEIgEAAQgGgZgOgPIABgIQAKhCAeguIgJAAQg8gKhMABIAAgDQg4gFg4AAIgIAAIhPAAQgWgOgiAVQgEABgFANQgRAogegcQAEAUANAKQADACAEAAQAPAkgigNIhtgnQBAA5gQAKQgVANgTgQQgEAAgBgBQgbg6ggArIAAgIQgBgghAAQQAZAigFAVQAAAAAAAAQAAABgBAAQAAAAgBAAQgBAAgBAAQgEAAgBgCQgYglhLgZQAgAsAqAiQACACAEAAQAeAdAzgFIAIAAQAJAiAnAGIAIAAQBBAfAtAzQACACAAAEQBBAsAuAtIgKAGQgTAPAGArIAAAQIAAAIIAAAYIAAAIIAAAIQAAAEgCACQgCACgEAAIAAAQIAAAJIgEAAQgHAggdAHIAAgIQAggxgOgvQgCgEAAgEQABAAABAAQABAAAAAAQABAAAAgBQABAAAAAAQAFgMgSAFQgCgJAAgGIAAgBQABgqgvgeQgdgbgjgVQg1gfAlgCQAAgEgCgBQgggdgegNQAAgEgCgDQgKgMgkgOQAVAqAGAVQAAABABAAQAAAAABAAQAAAAABAAQABAAABAAIAHACQAmAPADgBQAMAagXgMIgJgGQAUA6g4APQAMATAOgRQACgCAEAAQASBJAkAhQACACAAAEIgIAAIgIAAQAAAEACACQACACAEAAQAmBCBDAlQADACAEgBQBLBWA6BEQACADAAAEQhIg6AIBqIAAAIQAhAKBfAzIAAgFQggg7APgJQAFgEANAFQAPAHAIAMQANAWAegRQAMgHAdAWIAEgEQAEAAACACQACACAAAFIgIAAQAlBNATg5gAlgmUQAAAEACABQAWATARAYIAIAEQgCg0grAAIgEAAgAIrpXQBBAsANBfIAIAEQALh7hjgaQAAAFACABgAovqdQAxB+BeBTQAAgEgBgDQhEhthLhlIABAIgAPKoVQAEBAArgTQAAAAABAAQAAAAAAgBQAAAAABgBQAAgBAAgBQgwipijgwQgfgIgQAQQgFAGgHgKQgDgEgIAAIgIAAQhngChSgWQAzAhBWgBIAIAAQAAAEACACQAMARgMgCQBFAaAXAjQACACAAAEQAeALArAlQAPAMAIgbQAzBIAlgcgAGBs9IBeBLQACABAAAEQgEBVALA7IABAIQAsAVAQglIgEAAQgwgMgIg6QAAgCgGgDQgCgBAAgEQAggrgWgfQgCgCAAgEQB5AlB/gRIABgEQhJgcAfg2QACgCAAgEQgNgUg0AUQgmAOgyACQgggMAvgJQABAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAvgKAqgVQADgBAEgBIBIgFQAugEgNgeIgIgBQhEgahNA6IAAgDQglAKgLASQgEgBgDACQg1AOgkgHQAIgNgSgTQgzg4gzBHQASAJA1gcQAbgOgGAhQgDAPAHAiQgjATgdgggAHRpdQAAgHADgCIAFgDQgEgMgBgQQgGhOg9hCQAAAEABADQAMAcATAVIgEAAQAMA2gYAaIgEAAQAJAnArAJgA6Uv2QAUBFgGhkQgCgagCAAQgEAAgGA5gANqvmQAOAOAigEQBIgKAhgIIgIgBQgagIgcAAQgqAAgxARgAGpwXIAIABQAogMAKgYQAEgKAeAMQANAFgBANQAPgUg7gdQgNgHgXAAIABgIQANg+g+AOQgGAWAMAFQACABAAAEIgBAIQgDAygcgqQgEBJA0AGgAjfy+QAAABAAAAQAAABAAABQAAAAAAABQAAAAABAAQAoALAXAZQAIADABgBQAfgthEAAQgQAAgUADgABQy+IAIAAIAwAAIAIAAQA4APAfgSQABgBAAgEQA8AOBNgDIAAgDIAAgIQANABgFgSIAAgIQAOhOgGhiIAAgIIgBgEQgTgDgtgJIAABAIAAAIIgEABQgEAzggAVIAAAIQgQAigdgUQg9gpgOhWIgIABQglALgzgEQAMAwAEAhQACAVgSALIgEgBQgDgWgRgBQAAgEgCgFQgSgsgjgcIAAgLQgBAug3gDQAJAjAOAeQABADAAAFQABAPADAIIgEAAQgEAAgBgBQgNgQgOgOIAAgFQgJAggvgEQAHAdAaALIAHABQAYAMAOgOQACgDAAgDQAeAYBhADIAAgDIAIAAgAjMznQAGgJgWgIQgKgEgZAFQAAgDgCgCQhKhEhNgPQBFAgALAwIAAAIQgTAWAsgUQAEgCAEAAQBEAzAXgjgAp40GQAAABAAAAQAAABAAABQAAAAABABQAAAAAAAAQAqASAlARIAEAAQAAgohOAAIgGABgAtZ13IAIAAQA+AnBrAgIAHABIAIAAQAqAGg6geIAAgIQAMAAALgEQAAAAABAAQAAAAAAgBQAAAAAAgBQAAgBAAgBQAWAGAHgEIAMgGQAAgdhRgHQgEAAgCgCIgigeQAAgEgBgBQgmgUhJABIgIAAIgQAAQAAgBAAgBQAAgBAAAAQgBgBAAAAQAAAAAAgBQgfgLgoAAIAAgJIAAgIIAQAAIAIAAQAEATAHgQQABgDAEAAQBJALAzgOIgEAAQgtABAdgdQAzA4ABgoIAEAAQAEAAAEABQCVApCcgKQgUAAgQgEQiBgJiUgbQAAgFACgCQAegghIAXQAEgEACgFQACgEAAgEQABAAABAAQABAAAAAAQABAAAAAAQAAAAAAgBQAZg+hVAYIAAAIQgBAAgBgBQgBAAAAAAQgBAAAAAAQgBgBAAAAQgDgHAAgHQAEgBABgBQAuhXhbAYIAAgEQgQAKgQgOQAMAQAKARQACAEAAADQgEAAgDgCQgagMgXAWQgEAAgDgBQgsgggegvIAAAIIAAAIIgIAAIAAAgIAAAIQgEAAgCADQgLAKgPgVQAAgIgCAAQgTgGAHgKQAngyhBAaQgEAAgDgCQghgYgoASQAIAKAgAAQASAAAGAOQAEAYAVAHIAHABQAWAjAgAYQACABAAAFQAAAEgCABQgaATgcgQIAAAHIAAAIQgEAAgCgCQgUgTgmgCIAAAIIgIAAQhUAAhFAPQgVgBAJAZQASAUhGgDQAtAcBUAAQAwAAgIgMQARgoAggWQADgCAEgBQAZAXATAaIgEAAIAAgFQgFATgTARQA+A3BQAaQBDAXASgGQARgEAOAAQAMAAALADgAn42nQAIAYAYAHIAIABQBHBPgjhDIgCgBQgQgEgKgPQAAgEgCgDQgLgRgdAAIgGAAgAAY3YQAEA4BNgHQAdgEACgtIAAgDIhwADgAAH3/IAJAAQATAmAugdQADgBAEAAQgBg3gbg4QAAAAAAgBQgBAAAAAAQgBAAAAAAQgBgBgBAAQgdgFgZg8QgHgVgiAGQAAgEgBgDQgRgng+AeQAMARAIAWQAAAAAAAAQABABAAAAQABAAAAAAQABAAABAAQAgAVAcA1QAbA2gLALQgMALAAgOQgrAXBRACgAkP6AQAzAbgLAZQgJATAfAEQAmAGAVAfIAHAIQAcA+AIhWIgEAAQAAgDgBgBQhagqhdhSQgEAAgDgCQgigegwAQIAAAQIAAAIQAhBWBMg6IAAgEgAxb48QAAAAABABQAAAAAAAAQAAABAAABQAAABAAABQAEgzg8gNIgIgBIgBgEQhKgLguAXQgBAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAABQgNAZgfAFQApAZBfgNIABgDQAyABAtAKg");
	this.shape.setTransform(240.7,226.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(65));

	// Layer 1
	this.item_bg = new lib.Symbol5();
	this.item_bg.setTransform(468.9,239.8,1.188,1.188,0,0,0,425.6,210.1);
	this.item_bg.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.item_bg).wait(1).to({regX:425.9,regY:210.3,x:464.3,y:240.1,alpha:0.099},0).wait(1).to({x:459.3,alpha:0.198},0).wait(1).to({x:454.3,alpha:0.295},0).wait(1).to({x:449.3,alpha:0.392},0).wait(1).to({x:444.2,alpha:0.487},0).wait(1).to({x:439.2,alpha:0.581},0).wait(1).to({x:434.2,alpha:0.674},0).wait(1).to({x:429.2,alpha:0.767},0).wait(1).to({x:424.1,alpha:0.858},0).wait(1).to({x:419.1,alpha:0.948},0).wait(1).to({x:414.1,alpha:1},0).wait(1).to({x:409.1},0).wait(1).to({x:404.1},0).wait(1).to({x:399},0).wait(1).to({x:394},0).wait(1).to({x:389},0).wait(1).to({x:384},0).wait(1).to({x:378.9},0).wait(1).to({x:373.9},0).wait(1).to({x:368.9},0).wait(1).to({x:363.9},0).wait(1).to({x:358.9},0).wait(1).to({x:353.8},0).wait(1).to({x:348.8},0).wait(1).to({x:343.8},0).wait(1).to({x:338.8},0).wait(1).to({x:333.7},0).wait(1).to({x:328.7},0).wait(1).to({x:323.7},0).wait(1).to({x:318.7},0).wait(1).to({x:313.7},0).wait(1).to({x:308.6},0).wait(1).to({x:303.6},0).wait(1).to({x:298.6},0).wait(1).to({x:293.6},0).wait(1).to({x:288.5},0).wait(1).to({x:283.5,alpha:0.92},0).wait(1).to({x:278.5,alpha:0.828},0).wait(1).to({x:273.5,alpha:0.738},0).wait(1).to({x:268.5,alpha:0.65},0).wait(1).to({x:263.4,alpha:0.563},0).wait(1).to({x:258.4,alpha:0.478},0).wait(1).to({x:253.4,alpha:0.395},0).wait(1).to({x:248.4,alpha:0.313},0).wait(1).to({x:243.3,alpha:0.232},0).wait(1).to({x:238.3,alpha:0.153},0).wait(1).to({x:233.3,alpha:0.076},0).wait(1).to({x:228.3,alpha:0},0).wait(1).to({x:223.3},0).wait(1).to({x:218.2},0).wait(1).to({x:213.2},0).wait(1).to({x:208.2},0).wait(1).to({x:203.2},0).wait(1).to({x:198.1},0).wait(1).to({x:193.1},0).wait(1).to({x:188.1},0).wait(1).to({x:183.1},0).wait(1).to({x:178.1},0).wait(1).to({x:173},0).wait(1).to({x:168},0).wait(1).to({x:163},0).wait(1).to({x:158},0).wait(1).to({x:152.9,y:240.2},0).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(413.4,215.3,1011.8,499.6);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;